/**
 * Onboarding Configuration — the single, configuration-driven input to onboarding.
 *
 * TRACEABILITY
 *   Architecture : 21-tenant-lifecycle.md §3 (R-21.8, R-21.10, R-21.16) · §5 (ownership split)
 *   ADR          : ADR-0030 (TLM is the Platform Core onboarding orchestrator)
 *   Criteria     : C-21.4 (onboarding requires no code, deployment or schema change)
 *                  C-21.9 (neither side writes the other's configuration column)
 *   Invariant    : INV-2 (DBiz never receives a customer credential)
 *
 * ONE OBJECT ONBOARDS A TENANT. Adding a tenant is authoring this object and nothing
 * else — no code change, no deployment, no schema change (R-21.8). It is split by
 * OWNERSHIP, not convenience (R-21.16): the DBiz column and the customer column are
 * distinct types, so neither can be written where the other belongs (R-21.17, C-21.9).
 *
 * THERE IS NO CREDENTIAL FIELD ANYWHERE IN THIS SCHEMA, AND THAT IS STRUCTURAL.
 * Tool credentials and AI credentials are created and held by the customer, in their
 * tenancy (R-21.14, INV-2). The Intelligence Plane captures a provider *selection* so
 * it can generate the right adapter bindings — never a secret. A credential the
 * platform cannot represent is a credential it cannot leak. `onboarding-configuration.test.ts`
 * proves the absence by scanning the schema, so a future field cannot reintroduce one
 * unnoticed.
 *
 * Shape and validation only. No orchestration logic.
 */
import { z } from 'zod';
import { TechnologyProfileSchema, APPLICATION_TYPE_IDS } from '@dbiz/platform-core';

/** The six certifiable capabilities (R-11.4). Entitlement is a DBiz-owned decision. */
export const ENTITLED_CAPABILITIES = [
  'functional-testing',
  'dev-change',
  'inverse-flow-discovery',
  'performance',
  'security-testing',
  'penetration-testing',
] as const;

/**
 * AI is expressed as capability CLASSES, never as a product (INV-9, Rule 12). The
 * concrete provider is a customer-held, opaque handle resolved in the Execution Plane;
 * the Intelligence Plane never names a vendor and never holds the credential.
 */
export const AI_CAPABILITY_CLASSES = [
  'extraction', 'classification', 'generation', 'summarisation', 'ranking', 'reconciliation',
] as const;

const PROJECT_MANAGEMENT_PROVIDERS = ['jira', 'azure-devops', 'none'] as const;
const TEST_MANAGEMENT_PROVIDERS = ['zephyr-essential', 'zephyr-scale', 'xray', 'testrail', 'azure-test-plans', 'none'] as const;
const AUTHENTICATION_TYPES = ['none', 'form', 'oauth', 'saml', 'basic', 'custom'] as const;
const ENVIRONMENTS = ['development', 'test', 'staging', 'production'] as const;
/**
 * The class of application under test — the PRIMARY driver of everything the generator emits:
 * configuration schema, environment slots, authentication strategy, discovery strategy, execution
 * strategy, validation rules, portal schema and documentation.
 *
 * DERIVED FROM THE APPLICATION TEMPLATE REGISTRY, never restated. A hard-coded list here would be
 * a second source of truth: registering Salesforce would make it generatable but not selectable,
 * and the mismatch would surface as "unsupported application type" against a template that exists.
 * Deriving it means a registered template is selectable the moment it is registered, and an
 * unregistered id cannot be stored in a tenant configuration at all (C-03.17).
 */
export const APPLICATION_TYPES = APPLICATION_TYPE_IDS;
/** How the target enforces a second factor. `totp` is the only method an EP can drive unattended. */
export const MFA_METHODS = ['none', 'totp'] as const;

/**
 * ADR-0085 §4.1 — THE TENANT'S DISPOSITION TOWARD ITS TEST REPOSITORY.
 *
 * A tenant whose Azure DevOps project already holds a Test Plan and a tenant for whom one must be
 * created previously generated BYTE-IDENTICAL configurations. Not similar — indistinguishable. An
 * under-specified configuration has an empty slot a reader can see they have not answered; here
 * there was no slot, so there was no question.
 *
 * THIS FIELD IS A VALUE, NEVER AN INFERENCE, and it is REQUIRED WITH NO DEFAULT — which is a
 * deliberate break at the intake boundary (ADR-0085 §7). The rejected alternative is to infer the
 * disposition from whether the plan field is populated, and its reason is the ruling:
 *
 *   Identifier fields alone leave an empty plan slot ambiguous between "create one for me" and
 *   "not configured yet" — the Absent/Unreachable collapse one layer up, in CONFIGURATION, where
 *   no `fold()` demands all five handlers.
 *
 * The platform has ruled three times that a negative meaning two things must be split into two
 * values meaning one thing each (ADR-0072 for writes, ADR-0074 for reads, ADR-0074 §6.4.2 for
 * decisions). In all three THE TYPE WAS THE ENFORCEMENT. At this layer there is no type doing that
 * work: a JSON field is absent or it is not, and no conformance test greps a customer's config file
 * for an unhandled case. So `create-if-absent` and "nobody has filled this in yet" must be
 * DIFFERENT BYTES ON DISK.
 *
 * `must-exist` IS NOT A CONVENIENCE MEMBER. It is the disposition for a tenant whose test
 * repository is GOVERNED — where creating a plan is a change someone must approve, and a platform
 * that creates one silently has bypassed a control. Under `must-exist` a reached-and-absent
 * container is a REFUSAL (ADR-0071's outcome: the stage did its work and the answer is no).
 *
 * A two-member vocabulary was considered and the disagreement is RECORDED rather than merged away
 * (ADR-0085 §3): `reuse-existing` and `must-exist` both refuse on absence, but they refuse with
 * DIFFERENT REASONS, and the reason is what a customer acts on.
 *
 * `unknown` IS NOT A MEMBER HERE AND MUST NOT BECOME ONE. It is the disposition of a tenant record
 * generated before this field existed, it is produced only by normalisation (D-133), and it is
 * never a pass — CHARTER §17.1's `NOT MEASURED` rule applied to configuration. Admitting it at
 * intake would let a tenant DECLARE that they had not decided.
 */
export const TEST_REPOSITORY_DISPOSITIONS = ['reuse-existing', 'create-if-absent', 'must-exist'] as const;
export type TestRepositoryDisposition = (typeof TEST_REPOSITORY_DISPOSITIONS)[number];

/** ADR-0085 §4.2 ruling 4 — the discriminant `discoverGrouping` already returns. */
export const TEST_SUITE_KINDS = ['requirement-based', 'static'] as const;

/**
 * DBiz-OWNED COLUMN (R-21.16 left). Entitlements, policy, contract version. The
 * customer may not write these; that is enforced by them living in a distinct object.
 */
export const DbizConfigurationSchema = z.object({
  entitledCapabilities: z.array(z.enum(ENTITLED_CAPABILITIES)).min(1),
  contractVersion: z.string().min(1),
  retentionObligationDays: z.number().int().positive(),
}).strict();

/**
 * CUSTOMER-OWNED COLUMN (R-21.16 right). Selections and endpoints only — NEVER
 * credentials (INV-2). Each provider names WHICH tool, plus non-secret identifiers.
 */
export const CustomerConfigurationSchema = z.object({
  deployment: z.object({
    executionPlaneName: z.string().min(1),
    region: z.string().min(1),
  }).strict(),
  application: z.object({
    applicationName: z.string().min(1),
    applicationUrl: z.string().url(),
    /** Registered application classes — each selects an Application Template that drives generation. */
    applicationTypes: z.array(z.enum(APPLICATION_TYPES)).optional(),
    authenticationType: z.enum(AUTHENTICATION_TYPES),
    /**
     * Whether the target enforces a second factor at sign-in, and by which method. A DECLARATION,
     * never a credential: the TOTP enrolment secret is an env REFERENCE resolved at the EP (INV-2).
     * Sign-in targets commonly enforce it, and the EP must know before it drives a login.
     */
    mfa: z.object({
      required: z.boolean(),
      method: z.enum(MFA_METHODS).default('none'),
    }).strict().optional(),
    browserRequirements: z.array(z.string()).default([]),
  }).strict(),
  projectManagement: z.object({
    provider: z.enum(PROJECT_MANAGEMENT_PROVIDERS),
    project: z.string().optional(),
    board: z.string().optional(),
    repository: z.string().optional(),
  }).strict(),
  /**
   * ADR-0085. The four identifier/organisation concerns land here IN §4.2's DEPENDENCY ORDER, and
   * the order is the ruling rather than a plan: `baseUrl` FIRST, because an identifier with no
   * organisation to resolve it against identifies nothing, so plan and suite identity are
   * UNREACHABLE until it lands.
   *
   * THE SCHEMA IS THE FIRST EDIT, NOT THE LAST. This object is `.strict()`, so onboarding could not
   * capture a plan and the exporter had nothing to emit even if widened — and a field passed
   * through anyway is a VALIDATION FAILURE rather than a silently dropped one, which is correct.
   * Both layers move or neither (ADR-0085 §6.1).
   *
   * Four concerns, six fields: ruling 3's ID-wins rule requires the id and the name to be
   * SEPARATELY EXPRESSIBLE, since a name that disagrees with a resolved id must be recordable in
   * order to be recorded. They are not two ways to answer one question — they answer two different
   * moments. An ID resolves an EXISTING container; a name is what a CREATED container is called,
   * and no id can be configured for a container that does not exist yet. The dispositions map onto
   * them exactly: `must-exist` and `reuse-existing` consume the ID, `create-if-absent` the name.
   */
  testManagement: z.object({
    provider: z.enum(TEST_MANAGEMENT_PROVIDERS),
    projectKey: z.string().optional(),
    /**
     * ADR-0085 §4.1 — REQUIRED FOR EVERY TENANT THAT HAS A TEST TOOL, AND NO DEFAULT ANYWHERE.
     * Optional in the object, mandatory by the refinement below. See `TEST_REPOSITORY_DISPOSITIONS`.
     */
    repositoryDisposition: z.enum([...TEST_REPOSITORY_DISPOSITIONS, 'unknown']).optional(),
    /**
     * ADR-0085 §4.2 ruling 2 — the organisation root, and NOTHING WORKS WITHOUT IT.
     * The consuming plane's synchronisation adapter factory requires it and no other block can
     * lawfully supply it: reading `projectManagement.baseUrl` from a test-management code path
     * would couple two providers a tenant may legitimately host separately.
     */
    baseUrl: z.string().url().optional(),
    /** ADR-0085 §4.2 ruling 3 — plan identity. THE ID IS AUTHORITATIVE when both are present. */
    planId: z.string().min(1).optional(),
    /** Ruling 3 — what a CREATED plan is called. A name disagreeing with a resolved `planId` is RECORDED, never used to re-target. */
    planName: z.string().min(1).optional(),
    /** ADR-0085 §4.2 ruling 4 — suite identity, same rule. */
    suiteId: z.string().min(1).optional(),
    suiteName: z.string().min(1).optional(),
    /** Ruling 4 — the discriminant `discoverGrouping` already returns; a discovered value nothing can be compared against is a read whose result cannot be checked. */
    suiteKind: z.enum(TEST_SUITE_KINDS).optional(),
  }).strict().superRefine((tm, ctx) => {
    // ADR-0085 §4.1 AT THE INTAKE BOUNDARY — a deliberate break, and it is the schema that takes it.
    //
    // SCOPED TO TENANTS THAT HAVE A TEST TOOL, AND THE SCOPING IS NOT THE REJECTED INFERENCE.
    // §3 rejects inferring the DISPOSITION from whether the plan field is populated — deducing a
    // policy from an empty slot. This deduces nothing: `provider: 'none'` means the tenant has NO
    // test repository, so there is no disposition to hold rather than an unstated one. Requiring an
    // answer here would demand a meaningless declaration and then carry it as if it meant something.
    //
    // IT IS A REFINEMENT RATHER THAN A REQUIRED FIELD because the requirement is conditional and a
    // required field cannot express a condition. What it must NOT become is a default: the error
    // below refuses, and refusing is the whole point — `create-if-absent` and "nobody has filled
    // this in yet" have to be different bytes on disk.
    if (tm.provider !== 'none' && tm.repositoryDisposition === undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['repositoryDisposition'],
        message: 'a test-management provider is selected but no repository disposition is declared — an omitted disposition is REFUSED, never defaulted (ADR-0085 §4.1)',
      });
    }
    // `'unknown'` IS ADMITTED BY THE ENUM AND REFUSED HERE, and the split is deliberate.
    //
    // Admitting it lets a pre-ADR-0085 record be READ, round-tripped and SEEN to be un-migrated
    // (D-133). Refusing it here makes it NEVER A PASS — CHARTER §17.1's `NOT MEASURED` rule at the
    // configuration layer. If the enum rejected it outright, the marker could not be carried at
    // all, and an un-migrated tenant would fail with a malformed-value error that names neither the
    // cause nor the remedy — indistinguishable from a corrupt record.
    if (tm.provider !== 'none' && tm.repositoryDisposition === 'unknown') {
      ctx.addIssue({
        code: 'custom',
        path: ['repositoryDisposition'],
        message: 'this tenant was generated before a repository disposition existed, so its disposition is UNKNOWN and must not be read as create-if-absent — re-onboard or amend the record to declare one explicitly (ADR-0085 §5)',
      });
    }
  }),
  ai: z.object({
    /** Opaque, customer-supplied handle resolved in the EP. Never a vendor name here. */
    providerHandle: z.string().min(1),
    capabilityClasses: z.array(z.enum(AI_CAPABILITY_CLASSES)).default([]),
    routing: z.string().optional(),
  }).strict(),
  security: z.object({
    mutualTls: z.boolean(),
    oauth: z.boolean(),
    vault: z.boolean(),
  }).strict(),
}).strict();

/**
 * The whole input. `customerId`/`tenantName` identify the tenant; the technology
 * profile drives generation; the two columns keep ownership explicit.
 */
export const OnboardingConfigurationSchema = z.object({
  configurationVersion: z.literal('1.0.0'),
  customer: z.object({
    customerName: z.string().min(1),
    tenantName: z.string().min(1),
    businessUnit: z.string().min(1),
    environment: z.enum(ENVIRONMENTS),
  }).strict(),
  technologyProfile: TechnologyProfileSchema,
  dbiz: DbizConfigurationSchema,
  customerOwned: CustomerConfigurationSchema,
}).strict();

export type OnboardingConfiguration = z.infer<typeof OnboardingConfigurationSchema>;
export type DbizConfiguration = z.infer<typeof DbizConfigurationSchema>;
export type CustomerConfiguration = z.infer<typeof CustomerConfigurationSchema>;

export type ConfigurationRejection = {
  readonly ok: false;
  readonly reason: 'malformed';
  readonly detail: string;
};
export type ConfigurationAcceptance = {
  readonly ok: true;
  readonly configuration: OnboardingConfiguration;
};
export type ConfigurationResult = ConfigurationAcceptance | ConfigurationRejection;

/**
 * Validate configuration at onboarding. Returns a typed rejection rather than
 * throwing: onboarding must report WHICH stage failed and why (R-21.31).
 */
export function validateConfiguration(input: unknown): ConfigurationResult {
  const parsed = OnboardingConfigurationSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, reason: 'malformed', detail: parsed.error.issues[0]?.message ?? 'invalid configuration' };
  }
  return { ok: true, configuration: parsed.data };
}

/**
 * Substrings that would indicate a credential field. Used by the structural test to
 * prove none exists (INV-2). Kept beside the schema so the two move together.
 */
export const CREDENTIAL_MARKERS = [
  'password', 'secret', 'apikey', 'api-key', 'token', 'credential', 'privatekey', 'private-key',
] as const;
