/**
 * API documentation, generated from the contract schemas and the gateway's own surface.
 *
 * TRACEABILITY
 *   Architecture : 25-customer-success-model.md §7 · 20-cross-plane-contracts.md
 *   ADR          : ADR-0011 (contract distribution) · ADR-0021
 *   Criteria     : C-25.6 (API documentation generated from contract schemas)
 *                  C-25.9 (no real credentials, endpoints or tenant identifiers)
 *                  C-25.12 (the package is generated from validation output)
 *
 * R-25.18: the API surface is documented FROM the contract schemas, never maintained
 * separately. Hand-maintained API documentation diverges from the API, and the
 * divergence is invisible until a customer hits it.
 *
 * Two things follow from that, and both are enforced here rather than requested:
 *
 *   1. Schemas are READ from `packages/contracts/schema/*.json` — the same files the
 *      contract package publishes. Nothing is transcribed. If a schema changes and
 *      this document does not, the change simply appears.
 *
 *   2. Response codes and refusal reasons are supplied by the CALLER from the
 *      gateway's observed behaviour, not written here from memory. A documented `403`
 *      the gateway never returns is a promise nobody keeps.
 */

/** A refusal the gateway can actually produce, as observed from executing it. */
export interface ObservedResponse {
  readonly status: number;
  readonly reason: string;
  /** What the customer should do about it. A code without a remedy is a dead end. */
  readonly remedy: string;
}

export interface ApiSurface {
  /** Paths the gateway authorises, taken from its configuration rather than assumed. */
  readonly authorisedPaths: readonly string[];
  readonly observedResponses: readonly ObservedResponse[];
  readonly contractVersion: string;
}

export interface SchemaSource {
  /** Schema file name, e.g. `execution-package-v1.0.0.json`. */
  readonly name: string;
  /** Parsed JSON Schema, exactly as published. Never edited here. */
  readonly schema: Record<string, unknown>;
}

export interface OpenApiDocument {
  readonly openapi: string;
  readonly info: Record<string, unknown>;
  readonly servers: readonly Record<string, unknown>[];
  readonly components: Record<string, unknown>;
  readonly paths: Record<string, unknown>;
  readonly security: readonly Record<string, unknown>[];
}

/**
 * Synthetic values used throughout the documentation.
 *
 * R-25.27: examples use values that are RECOGNISABLY synthetic, so a copied example
 * cannot accidentally target a real system. `.example` and `.test` are reserved by
 * RFC 2606 and resolve nowhere; `tenant-example` is not a tenant identifier shape any
 * real tenant will hold.
 */
export const SYNTHETIC = {
  tenantId: 'tenant-example',
  host: 'gateway.example.test',
  registrationEndpoint: 'https://gateway.example.test/v1/register',
  oneTimeCredential: 'otc-example-single-use-value',
  runId: 'run-example-0001',
  correlationId: 'corr-example-0001',
  capabilityId: 'functional-testing',
} as const;

/**
 * Build the OpenAPI document.
 *
 * Every schema in `sources` becomes a component, referenced rather than inlined, so a
 * reader following a `$ref` lands on the published contract rather than on a copy
 * that has begun to drift.
 */
export function generateOpenApi(surface: ApiSurface, sources: readonly SchemaSource[]): OpenApiDocument {
  const schemas: Record<string, unknown> = {};
  // Sorted: map-iteration order must not leak into generated bytes, or the document
  // fails the determinism requirement it inherits from the generator (C-03.18).
  for (const s of [...sources].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    schemas[componentNameFor(s.name)] = stripDialectKeys(s.schema);
  }

  const responses: Record<string, unknown> = {};
  for (const r of [...surface.observedResponses].sort((a, b) => a.status - b.status || (a.reason < b.reason ? -1 : 1))) {
    responses[responseKey(r)] = {
      description: `${r.reason}. ${r.remedy}`,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Refusal' },
          example: { status: r.status, reason: r.reason },
        },
      },
    };
  }

  schemas['Refusal'] = {
    type: 'object',
    required: ['status', 'reason'],
    properties: {
      status: { type: 'integer', description: 'HTTP-equivalent status the gateway returned.' },
      reason: { type: 'string', description: 'Why the request was refused. Always present on a refusal.' },
    },
    description: 'Every refusal carries a reason. A refusal without one is indistinguishable from a fault.',
  };

  const paths: Record<string, unknown> = {};
  for (const p of [...surface.authorisedPaths].sort()) {
    paths[p] = {
      post: {
        summary: `Invoke ${p}`,
        description: [
          'Requires BOTH a client certificate and an OAuth access token bound to that',
          'certificate. Either alone is refused. The tenant is taken from the certificate;',
          'a tenant identifier supplied in the request body is treated as an attack.',
        ].join(' '),
        operationId: operationIdFor(p),
        security: [{ mutualTLS: [], oauth2: [] }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ExecutionPackage' },
              example: exampleRequest(surface.contractVersion),
            },
          },
        },
        responses: Object.fromEntries([
          ['200', {
            description: 'Accepted and served.',
            content: {
              'application/json': {
                example: { status: 200, tenantId: SYNTHETIC.tenantId, body: { accepted: true } },
              },
            },
          }],
          ...[...surface.observedResponses]
            .sort((a, b) => a.status - b.status)
            .map((r) => [String(r.status), { $ref: `#/components/responses/${responseKey(r)}` }] as const),
        ]),
      },
    };
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'DBiz Agentic QA Platform — Intelligence Plane API',
      version: surface.contractVersion,
      description: [
        'Generated from the published contract schemas and from the gateway\'s observed',
        'behaviour. It is not maintained by hand.',
        '',
        'The Execution Plane always initiates. The Intelligence Plane never opens a',
        'connection into a customer tenancy, for any purpose.',
      ].join('\n'),
      license: { name: 'UNLICENSED' },
    },
    servers: [{
      url: `https://${SYNTHETIC.host}`,
      description: 'Synthetic host. Replace with the endpoint issued during onboarding.',
    }],
    components: {
      securitySchemes: {
        mutualTLS: {
          type: 'mutualTLS',
          description: [
            'A client certificate issued to your tenant during registration. The tenant is',
            'bound in the subject CN and in a SAN URI (urn:dbiz:tenant:<id>). Certificates',
            'rotate; the previous certificate keeps working until it is revoked.',
          ].join(' '),
        },
        oauth2: {
          type: 'oauth2',
          description: [
            'An access token bound to the certificate key via the `cnf.kid` confirmation',
            'claim. Presenting the token on a different certificate is refused: a stolen',
            'token is useless without the private key it was bound to.',
          ].join(' '),
          flows: {
            clientCredentials: {
              tokenUrl: `https://${SYNTHETIC.host}/v1/token`,
              scopes: { 'execution:invoke': 'Submit execution packages for your tenant.' },
            },
          },
        },
      },
      schemas,
      responses,
    },
    paths,
    security: [{ mutualTLS: [], oauth2: [] }],
  };
}

/**
 * The error catalogue, as a table a human reads rather than a schema a tool reads.
 *
 * Generated from the same observed responses as the OpenAPI document, so the two
 * cannot disagree — which they would within one release if maintained separately.
 */
export function generateErrorCatalogue(surface: ApiSurface): string {
  const rows = [...surface.observedResponses]
    .sort((a, b) => a.status - b.status || (a.reason < b.reason ? -1 : 1))
    .map((r) => `| \`${r.status}\` | ${r.reason} | ${r.remedy} |`);

  return [
    '# Error catalogue',
    '',
    '**Generated from the gateway\'s observed behaviour.** Every entry below was produced',
    'by executing the gateway, not by reading its source. A status this table does not',
    'list is a status the gateway was not observed to return.',
    '',
    '| Status | Reason | What to do |',
    '|---|---|---|',
    ...rows,
    '',
    '## Reading a refusal',
    '',
    'Every refusal carries a `reason`. If you receive a refusal without one, that is a',
    'platform defect and worth reporting — the platform gates on refusals being explained.',
    '',
    '`401` means the platform could not establish **who you are**. `403` means it knows',
    'who you are and you asked for something else\'s. The distinction matters when you are',
    'debugging: a `403` will never be fixed by reissuing a certificate.',
    '',
  ].join('\n');
}

/** Authentication walkthrough, generated so its values match the examples elsewhere. */
export function generateAuthenticationGuide(surface: ApiSurface): string {
  return [
    '# Authenticating',
    '',
    'Two credentials are required together, and neither works alone.',
    '',
    '| | What it proves | Where it comes from |',
    '|---|---|---|',
    '| Client certificate | Which tenant is calling | Issued during registration |',
    '| Access token | That the call is currently authorised | Issued against the certificate |',
    '',
    '## Why both',
    '',
    'A certificate alone cannot expire quickly enough to be a session. A token alone can',
    'be copied. Binding the token to the certificate key (`cnf.kid`) means a token lifted',
    'from a log is useless without the private key — which never leaves your tenancy.',
    '',
    '## Obtaining them',
    '',
    'You do not request them. **Registration issues both**, once, in exchange for the',
    'one-time credential embedded in your generated solution:',
    '',
    '```json',
    JSON.stringify({
      tenantId: SYNTHETIC.tenantId,
      registrationEndpoint: SYNTHETIC.registrationEndpoint,
      oneTimeRegistrationCredential: SYNTHETIC.oneTimeCredential,
    }, null, 2),
    '```',
    '',
    'That credential is **consumed on first use**. Registering twice with it does not',
    'fail — it returns the grant you already hold. Registration is idempotent by tenant,',
    'so a retried deployment cannot produce a second identity.',
    '',
    '## Calling the API',
    '',
    '```json',
    JSON.stringify(exampleRequest(surface.contractVersion), null, 2),
    '```',
    '',
    'Send a `nonce` you have not sent before. A repeated nonce is refused — that is replay',
    'protection, and it is not optional.',
    '',
    '## Rotation',
    '',
    'Certificates rotate without redeploying anything. The previous certificate keeps',
    'working until it is explicitly revoked, so there is no moment where your deployment',
    'must restart in lockstep with the platform. Fetch the new one, start using it, and',
    'the old one falls away.',
    '',
    '## What is never sent',
    '',
    'Your private key. Your source. Your test data. Your screenshots. The platform stores',
    'none of them, and the absence is verified on every build rather than promised here.',
    '',
  ].join('\n');
}

// ── helpers ─────────────────────────────────────────────────────────────────

function exampleRequest(contractVersion: string): Record<string, unknown> {
  return {
    path: '/v1/execute',
    // A PLACEHOLDER, not a truncated JWT. A realistic-looking token teaches nothing a
    // customer needs and reads as a credential to every scanner that meets it —
    // including this platform's own, which is how this line came to be written twice.
    token: '<access-token-issued-during-registration>',
    nonce: 'nonce-example-0001',
    body: {
      contractVersion,
      runId: SYNTHETIC.runId,
      correlationId: SYNTHETIC.correlationId,
      capabilityId: SYNTHETIC.capabilityId,
      operations: [{ operationId: 'op-example-0001', kind: 'navigate', target: 'https://app.example.test/' }],
    },
  };
}

/** `execution-package-v1.0.0.json` -> `ExecutionPackage`. */
function componentNameFor(fileName: string): string {
  return fileName
    .replace(/-v\d+\.\d+\.\d+\.json$/, '')
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

function operationIdFor(p: string): string {
  const parts = p.split('/').filter(Boolean);
  return parts.map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1))).join('');
}

function responseKey(r: ObservedResponse): string {
  return `${r.status}${r.reason.replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^./, (c) => c.toUpperCase())}`;
}

/**
 * Remove the dialect keys that belong to a standalone schema document.
 *
 * `$schema` and `$id` are correct in the published file and wrong inside an OpenAPI
 * `components/schemas` entry, where they would re-anchor resolution and break `$ref`.
 * The schema's CONTENT is untouched — only its document framing is dropped.
 */
function stripDialectKeys(schema: Record<string, unknown>): Record<string, unknown> {
  const { $schema, $id, ...rest } = schema as Record<string, unknown> & { $schema?: unknown; $id?: unknown };
  void $schema;
  void $id;
  return rest;
}
